name: 构建镜像
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: 构建镜像：ubuntu-vnc
    env:
      IMAGE_NAME: ubuntu-vnc
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Buildx
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
